services:
  - type: web
    name: enzo-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:10000
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        value: ${{ secrets.OPENAI_API_KEY }}
